### ISSUE TITLE
Namespace for RPLidar node for Multirobot navigation

### ISSUE THREAD

**Issue by ipa-rar** [turtlebot/turtlebot4_robot#16]
**Describe the the feature you would like**
RPlidar node does not accept namespace in the launch file but the Lidar node can accept namespace. If this is added to the launch file of standard and lite it would be useful for the multi-robot scenarios.

**Comment by roni-kreinin** [comment]
The rplidar node gets namespaced by the PushRosNamespace action. https://github.com/turtlebot/turtlebot4_robot/blob/3d92a3f2b7ea889e198352322e231a7fab540dcf/turtlebot4_bringup/launch/standard.launch.py#L73
