### ISSUE TITLE
Camera pub frequency drops heavily when subscriber.

### ISSUE THREAD

**Issue by Fran-FC** [turtlebot/turtlebot4_robot#21]
**Please provide the following information:**
 - OS: Ubuntu 22.04LTS
 - ROS Distro: Humble with FastDDS and Discovery Server
 - Built from source or installed: installed
 - Package version:  ros-humble-turtlebot4-bringup: 1.0.1-1jammy.20230516.175706
 
The pub frequency of `/oakd/stereo/image_raw` and /oakd/rgb/image_raw` are published at a rate of 30hz without subscribers. But when a node subscribed to one of the camera's topics the frequency drops.

Case 1: If the subscriber is running in the raspberry pi, the pub rate drops *from 30hz to 17hz* more or less.
Case 2: But if the subscriber running in an external device (communicating via 5Ghz wifi) the publish rate *drops to less than 2hz*.

**Without subscribers**
```
ubuntu@raspberry:~$ ros2 topic hz /oakd/stereo/image_raw
average rate: 29.499
	min: 0.023s max: 0.048s std dev: 0.00542s window: 31
```

**Case 1: With one subscriber running in the raspberry pi**
```
ubuntu@raspberry:~$ ros2 topic hz /oakd/stereo/image_raw
average rate: 17.994
	min: 0.019s max: 0.194s std dev: 0.03152s window: 39
```
*Case 1: CPU usage very high when subscriber in RaspberryPi*
![image](https://github.com/turtlebot/turtlebot4_robot/assets/72190914/1b00a616-ae54-491d-afde-0738510a4a32)

**Case 2: With one subscriber running in a laptop**
```
ubuntu@raspberry:~$ ros2 topic hz /oakd/stereo/image_raw
average rate: 1.332
	min: 0.466s max: 0.901s std dev: 0.20136s window: 3
```

In *case 2* the problem seems to be a combination of network bandwith and CPU.
**WiFi connection benchmark:**
```
[ ID] Interval           Transfer     Bitrate
[  5]   0.00-1.00   sec  6.19 MBytes  51.9 Mbits/sec                  
```
**Camera bandwith greater than netwotrk bw**:
```
ubuntu@raspberry:~$ ros2 topic bw /oakd/stereo/image_raw
Subscribed to [/oakd/stereo/image_raw]
58.47 MB/s from 30 messages
	Message size mean: 1.84 MB min: 1.84 MB max: 1.84 MB
``` 

**To Reproduce**
Provide the steps to reproduce:
1. run oakd container node
2. run `ros2 topic echo /oakd/stereo/image_raw` and `ros2 topic hz /oakd/stereo/image_raw`
3. see the error

**Other notes**
Maybe is a middleware problem or even an error of the oakd camera software, but I feel it should have been tested.

**Comment by euivmar** [comment]
Has anyone else experienced these problems with the camera?

**Comment by hilary-luo** [comment]
This issue is being closed due to inactivity. If you are still experiencing the issue, feel free to reopen this ticket when you are ready to continue the troubleshooting process.
