### ISSUE TITLE
Is Turtlebot4_robot a package in the Ubuntu repos?

### ISSUE THREAD

**Issue by DingoOz** [turtlebot/turtlebot4_robot#4]
I am having an issuing installing turtlebot4_robot on Ubuntu 20.04 so that I can launch the turtlebot4 bringup.

Is the intent to have a package like "ros-galactic-turtlebot4-robot" or something like "ros-galatic-turtlebot4-bringup"?

...or is the intent to have a different installation processs?

**Comment by roni-kreinin** [comment]
turtlebot4_robot has not yet been released as we are waiting for the depthai-ros packages to be released. In the meantime you can build it from source by creating a workspace, cloning this package into the source folder, and building the workspace.

**Comment by roni-kreinin** [comment]
See https://turtlebot.github.io/turtlebot4-user-manual/software/turtlebot4_packages.html#source-installation-1

**Comment by DingoOz** [comment]
Wonderful, that is the answer that help the most.  Thank you for the super-quick reply. Cheers.

**Comment by roni-kreinin** [comment]
`turtlebot4_robot` is now available on the `ros2-testing` package server, and will be on the `ros2` package server with the next Galactic sync.
