### ISSUE TITLE
Depthai-ros main branch doesn't exist anymore

### ISSUE THREAD

**Issue by Guillaumebeuzeboc** [turtlebot/turtlebot4_robot#6]
The [dependencies.repo](https://github.com/turtlebot/turtlebot4_robot/blob/galactic/dependencies.repos) is listing the repository from [depthai-ros on the branch main](https://github.com/turtlebot/turtlebot4_robot/blob/galactic/dependencies.repos#L9). But the `main` branch doesn't exist any more on the [depthai-ros](https://github.com/luxonis/depthai-ros/branches) repo.
Instead, there is `main-old` and `ros-release` branch. I assume that the `dependencies.repo` should point to one of these branches.

**Comment by roni-kreinin** [comment]
I think I will just remove `dependencies.repo` as all of those packages have now been released. Good catch though.
