### ISSUE TITLE
tf transforms published by RPi and Create3 are not time synced

### ISSUE THREAD

**Issue by Yadunund** [turtlebot/turtlebot4_robot#8]
**Please provide the following information:**
The RPi publishes the `base_link<->rplidar_link` tf while the Create publishes the `odom<->base_link` tf. But it seems that both boards are not time synced and hence Rviz and other nodes that need to lookup `odom<->rplida_link` tfs complain due to unsuccessful tf lookups. This prevents me from running `amcl` for example.
```
[ERROR] [1663860176.643343209] [rviz2]: Lookup would require extrapolation into the future.  Requested time 1663860176.712678 but the latest data is at time 1663860176.611400, when looking up transform from frame [rplidar_link] to frame [odom]
```

 **Expected behaviour**
The clocks on the boards are synced or a systemctl service exists to keep them in sync

 **Actual behaviour**
Clocks on the boards are not synced

**To Reproduce**
Provide the steps to reproduce:
1. Start tb4
2. Launch rviz
3. Subscribe to /scan
4. Change global frame to odom
5. The laser scan will be displayed once in a while.
6. Switch global frame to base_link
7. Scan displayed consistently

**Other notes**
Add anything else you thing is important.

**Comment by roni-kreinin** [comment]
We use `chrony` for syncing the clocks between the RPi and Create 3. The config is [here](https://github.com/turtlebot/turtlebot4_setup/blob/galactic/conf/chrony.conf).

Can you access the Create 3 webserver and check the logs for any ntp warnings? Also, does this issue persist through a reboot?

**Comment by Yadunund** [comment]
Thanks for the quick response!
Is the `chrony` Daemon running by default on the RPi with that conf file?

I'll check the logs tomorrow and get back to you. But the problem persisted through reboots. 

To clarify, the tf lookup error is thrown on my PC that is on the same WiFi network as the RPi and Create3 boards. So maybe there needs to be a way to sync the times on all 3 devices?

**Comment by roni-kreinin** [comment]
You can try to set up `chrony` on your PC and have your PC sync the clock of the RPi in the same way that the RPi syncs the Create 3. Or try changing your NTP server to the same ones that the RPi uses:
```
pool ntp.ubuntu.com        iburst maxsources 4
pool 0.ubuntu.pool.ntp.org iburst maxsources 1
pool 1.ubuntu.pool.ntp.org iburst maxsources 1
pool 2.ubuntu.pool.ntp.org iburst maxsources 2
```

**Comment by luca-della-vedova** [comment]
Hi @roni-kreinin 

We can reproduce the issue on another robot, even setting the workstation to use the same chrony configuration as the Pi4 doesn't seem to help.
I looked at the logs for the create board and indeed there are some ntp related errors, below searching for `ntp` in a one hour run:

```
Oct  4 09:33:55 iRobot-9F25B7D69CBA44768C4850897AB74787 user.notice ntpd: ntpd: bad address '3.irobot.pool.ntp.org'
Oct  4 09:33:56 iRobot-9F25B7D69CBA44768C4850897AB74787 user.notice ntpd: ntpd: timed out waiting for 192.168.186.1, reach 0x00, next query in 32s
Oct  4 09:34:44 iRobot-9F25B7D69CBA44768C4850897AB74787 user.notice ntpd: ntpd: timed out waiting for 192.168.186.1, reach 0x00, next query in 33s
Oct  4 09:35:33 iRobot-9F25B7D69CBA44768C4850897AB74787 user.notice ntpd: ntpd: timed out waiting for 192.168.186.1, reach 0x00, next query in 33s
Oct  4 09:35:50 iRobot-9F25B7D69CBA44768C4850897AB74787 user.notice ntpd: ntpd: timed out waiting for 194.0.5.123, reach 0x0e, next query in 33s
Oct  4 09:35:50 iRobot-9F25B7D69CBA44768C4850897AB74787 user.notice ntpd: ntpd: timed out waiting for 218.186.3.36, reach 0x0e, next query in 33s
Oct  4 09:36:06 iRobot-9F25B7D69CBA44768C4850897AB74787 user.notice ntpd: ntpd: timed out waiting for 192.168.186.3, reach 0x3e, next query in 33s
Oct  4 09:36:23 iRobot-9F25B7D69CBA44768C4850897AB74787 user.notice ntpd: ntpd: timed out waiting for 192.168.186.1, reach 0x00, next query in 32s
Oct  4 09:36:40 iRobot-9F25B7D69CBA44768C4850897AB74787 user.notice ntpd: ntpd: timed out waiting for 218.186.3.36, reach 0x1c, next query in 32s
Oct  4 09:36:40 iRobot-9F25B7D69CBA44768C4850897AB74787 user.notice ntpd: ntpd: reply from 192.168.186.3: delay 0.003168 is too high, ignoring
Oct  4 09:37:12 iRobot-9F25B7D69CBA44768C4850897AB74787 user.notice ntpd: ntpd: timed out waiting for 192.168.186.1, reach 0x00, next query in 33s
Oct  4 09:38:01 iRobot-9F25B7D69CBA44768C4850897AB74787 user.notice ntpd: ntpd: timed out waiting for 192.168.186.1, reach 0x00, next query in 67s
Oct  4 09:38:01 iRobot-9F25B7D69CBA44768C4850897AB74787 user.notice ntpd: ntpd: timed out waiting for 218.186.3.36, reach 0x72, next query in 66s
Oct  4 09:39:25 iRobot-9F25B7D69CBA44768C4850897AB74787 user.notice ntpd: ntpd: timed out waiting for 192.168.186.1, reach 0x00, next query in 67s
Oct  4 09:40:48 iRobot-9F25B7D69CBA44768C4850897AB74787 user.notice ntpd: ntpd: timed out waiting for 192.168.186.1, reach 0x00, next query in 67s
Oct  4 09:40:58 iRobot-9F25B7D69CBA44768C4850897AB74787 user.notice ntpd: ntpd: reply from 192.168.186.3: delay 0.002612 is too high, ignoring
Oct  4 09:42:11 iRobot-9F25B7D69CBA44768C4850897AB74787 user.notice ntpd: ntpd: timed out waiting for 192.168.186.1, reach 0x00, next query in 134s
Oct  4 09:42:42 iRobot-9F25B7D69CBA44768C4850897AB74787 user.notice ntpd: ntpd: timed out waiting for 218.186.3.36, reach 0x2e, next query in 131s
Oct  4 09:44:42 iRobot-9F25B7D69CBA44768C4850897AB74787 user.notice ntpd: ntpd: timed out waiting for 192.168.186.1, reach 0x00, next query in 135s
Oct  4 09:45:09 iRobot-9F25B7D69CBA44768C4850897AB74787 user.notice ntpd: ntpd: timed out waiting for 218.186.3.36, reach 0x5c, next query in 133s
Oct  4 09:47:15 iRobot-9F25B7D69CBA44768C4850897AB74787 user.notice ntpd: ntpd: timed out waiting for 192.168.186.1, reach 0x00, next query in 132s
Oct  4 09:49:43 iRobot-9F25B7D69CBA44768C4850897AB74787 user.notice ntpd: ntpd: timed out waiting for 192.168.186.1, reach 0x00, next query in 134s
Oct  4 09:52:13 iRobot-9F25B7D69CBA44768C4850897AB74787 user.notice ntpd: ntpd: timed out waiting for 192.168.186.1, reach 0x00, next query in 261s
Oct  4 09:52:20 iRobot-9F25B7D69CBA44768C4850897AB74787 user.notice ntpd: ntpd: timed out waiting for 139.99.61.186, reach 0xfe, next query in 257s
Oct  4 09:54:07 iRobot-9F25B7D69CBA44768C4850897AB74787 user.notice ntpd: ntpd: timed out waiting for 194.0.5.123, reach 0xfe, next query in 270s
Oct  4 09:56:33 iRobot-9F25B7D69CBA44768C4850897AB74787 user.notice ntpd: ntpd: timed out waiting for 162.159.200.123, reach 0xfe, next query in 261s
Oct  4 09:56:50 iRobot-9F25B7D69CBA44768C4850897AB74787 user.notice ntpd: ntpd: timed out waiting for 192.168.186.1, reach 0x00, next query in 264s
Oct  4 09:56:53 iRobot-9F25B7D69CBA44768C4850897AB74787 user.notice ntpd: ntpd: timed out waiting for 139.99.61.186, reach 0xfc, next query in 269s
Oct  4 09:58:23 iRobot-9F25B7D69CBA44768C4850897AB74787 user.notice ntpd: Script called in periodic mode
Oct  4 09:58:37 iRobot-9F25B7D69CBA44768C4850897AB74787 user.notice ntpd: ntpd: reply from 194.0.5.123: delay 0.018513 is too high, ignoring
Oct  4 10:01:31 iRobot-9F25B7D69CBA44768C4850897AB74787 user.notice ntpd: ntpd: timed out waiting for 192.168.186.1, reach 0x00, next query in 521s
Oct  4 10:01:39 iRobot-9F25B7D69CBA44768C4850897AB74787 user.notice ntpd: ntpd: timed out waiting for 139.99.61.186, reach 0xf8, next query in 516s
Oct  4 10:09:24 iRobot-9F25B7D69CBA44768C4850897AB74787 user.notice ntpd: Script called in periodic mode
Oct  4 10:10:28 iRobot-9F25B7D69CBA44768C4850897AB74787 user.notice ntpd: ntpd: timed out waiting for 192.168.186.1, reach 0x00, next query in 521s
Oct  4 10:10:31 iRobot-9F25B7D69CBA44768C4850897AB74787 user.notice ntpd: ntpd: timed out waiting for 139.99.61.186, reach 0xf0, next query in 524s
Oct  4 10:14:22 iRobot-9F25B7D69CBA44768C4850897AB74787 user.notice ntpd: ntpd: timed out waiting for 162.159.200.123, reach 0xf6, next query in 525s
Oct  4 10:19:15 iRobot-9F25B7D69CBA44768C4850897AB74787 user.notice ntpd: ntpd: reply from 139.99.61.186: delay 0.015488 is too high, ignoring
Oct  4 10:19:25 iRobot-9F25B7D69CBA44768C4850897AB74787 user.notice ntpd: ntpd: timed out waiting for 192.168.186.1, reach 0x00, next query in 536s
Oct  4 10:20:25 iRobot-9F25B7D69CBA44768C4850897AB74787 user.notice ntpd: Script called in periodic mode
Oct  4 10:23:25 iRobot-9F25B7D69CBA44768C4850897AB74787 user.notice ntpd: ntpd: timed out waiting for 162.159.200.123, reach 0xec, next query in 516s
```

It seems most of them time out and the ones that succeed are ignored because of a too high delay

**Comment by roni-kreinin** [comment]
@luca-della-vedova Can you try running `sudo apt install ntpdate` and `sudo ntpdate ntp.ubuntu.com` on both the RPi and remote PC?

**Comment by Yadunund** [comment]
>@luca-della-vedova Can you try running sudo apt install ntpdate and sudo ntpdate ntp.ubuntu.com on both the RPi and remote PC?

I tried this but doesn't help. It has been very challenging for us to run tb4 as a result of this.
This might be a related issue: https://github.com/turtlebot/turtlebot4/issues/62

I'm able to subscribe to all the topics but the tfs are not time synced. 

The interesting this is that when I reflash the SD card on the RPi and reboot for the first time, it works. But it quickly goes out of sync. Any other insights would be greatly appreciated.

**Comment by roni-kreinin** [comment]
Is it possible that your WiFi network is blocking access to the NTP servers? Similar to https://github.com/turtlebot/turtlebot4/issues/10?

**Comment by Jayden-F** [comment]
Hello @roni-kreinin,

I am encountering difficulties in setting up AMCL on my TurtleBot4 robot. I believe this issue to be the root cause of my problems. The error message I am receiving states that the consecutive laser scan transforms have failed due to a time synchronization issue, with the latest data being in the past compared to the requested time.

**The error states**
> Consecutive laser scan transforms failed: (Lookup would require extrapolation into the future. Requested time 1675292943.069337 but the latest data is at time 1675292943.062120, when looking up transform from frame [base_footprint] to frame [odom]

Additionally, https://github.com/ros-planning/navigation2/issues/3390 will further explain my issue.

I have attempted various suggested solutions to resolve the issue, but the Create3 still ignores the time and the problem persists. Despite rebooting the device multiple times through the webserver, the delay remains an issue.
https://iroboteducation.github.io/create3_docs/setup/compute-ntp/

Even with @teufelweich's suggestion to establish an NTP server, the Create3 still ignores it due to a persistent time delay issue.
https://github.com/turtlebot/turtlebot4/issues/10#issuecomment-1398092018

**Comment by Yadunund** [comment]
What worked for me in the end was to have the create board and RPi connected to a network that is not connected to the internet.

**Comment by Jayden-F** [comment]
Thanks, @Yadunund. 
It seems the system time isn't the issue. Instead, it may be due to the fact that some of the tf tree is published by create3 and some by the rpi, causing it to never be time synced. Has anyone had success with running AMCL on a real TB4?

**Comment by Yadunund** [comment]
Yeah I can confirm that I have gotten AMCL and navigation to run smoothly once the network is isolated.

**Comment by Jayden-F** [comment]
I have tried with an isolated network. I set up my remote pc as a chrony host to serve time to the rpi. However, the create3 refuses to update its time.

> Feb  3 03:33:29 wall-e-3 user.notice ntpd: ntpd: bad address '3.irobot.pool.ntp.org'
Feb  3 03:33:34 wall-e-3 user.notice ntpd: ntpd: bad address '2.irobot.pool.ntp.org'
Feb  3 03:33:39 wall-e-3 user.notice ntpd: ntpd: bad address '1.irobot.pool.ntp.org'
Feb  3 03:33:44 wall-e-3 user.notice ntpd: ntpd: bad address '0.irobot.pool.ntp.org'
Feb  3 03:34:01 wall-e-3 user.notice ntpd: ntpd: timed out waiting for 192.168.186.1, reach 0x00, next query in 32s
Feb  3 03:34:17 wall-e-3 user.notice ntpd: ntpd: bad address '3.irobot.pool.ntp.org'
Feb  3 03:34:22 wall-e-3 user.notice ntpd: ntpd: bad address '2.irobot.pool.ntp.org'
Feb  3 03:34:27 wall-e-3 user.notice ntpd: ntpd: bad address '1.irobot.pool.ntp.org'
Feb  3 03:34:32 wall-e-3 user.notice ntpd: ntpd: bad address '0.irobot.pool.ntp.org'
Feb  3 03:34:32 wall-e-3 user.notice ntpd: ntpd: reply from 192.168.186.3: delay 0.005164 is too high, ignoring
Feb  3 03:34:50 wall-e-3 user.notice ntpd: ntpd: timed out waiting for 192.168.186.1, reach 0x00, next query in 33s
Feb  3 03:35:37 wall-e-3 user.notice ntpd: ntpd: bad address '3.irobot.pool.ntp.org'
Feb  3 03:35:42 wall-e-3 user.notice ntpd: ntpd: bad address '2.irobot.pool.ntp.org'
Feb  3 03:35:47 wall-e-3 user.notice ntpd: ntpd: bad address '1.irobot.pool.ntp.org'
Feb  3 03:35:53 wall-e-3 user.notice ntpd: ntpd: bad address '0.irobot.pool.ntp.org'
Feb  3 03:35:53 wall-e-3 user.notice ntpd: ntpd: timed out waiting for 192.168.186.1, reach 0x00, next query in 33s
Feb  3 03:35:53 wall-e-3 user.notice ntpd: ntpd: reply from 192.168.186.3: delay 0.007773 is too high, ignoring


For which the create3 documentation have a solution which also does not work.
> user.notice ntpd: ntpd: reply from 192.168.186.3: delay ### is too high, ignoring
If this happens, simply restart the robot (not just the application) via the webserver over the USB network connection.

**Comment by teufelweich** [comment]
@Jayden-F it took several reboots for me too. try rebooting the whole robot through the buttons

**Comment by roni-kreinin** [comment]
@Jayden-F Can you try to comment out this line in `/etc/chrony.conf` on the RPi4:

`server 192.168.186.2 presend 0 minpoll 0 maxpoll 0 iburst  prefer trust`

Then restart the chrony service.

**Comment by Jayden-F** [comment]
@teufelweich The robot is finally able to localize after multiple restarts. However, since I will be using multiple robots, the current solution is not ideal. 

@roni-kreinin Thank you, I have commented out this line. 

What would be nice if we could ssh into the create3 and configure the chrony service ourselves.

**Comment by Fran-FC** [comment]
I also have problems with time sync. I have a PC which acts as a router giving WIFI to the Raspberry, I use the Discovery Server network configuration, so the Create 3 traffic is routed through the Raspberry. 

I have configured my PC to be a Chrony server and the Raspberry as its client. This time synchronization performs well, but the Create 3 syncs very strangely, because it picks the date well, but with 2 hours of delay. I might think it is because the UTC setting or a locale setting? I don't know how to change this to be in sync with the PC and the Raspberry...

Any suggestions?

The time displays of each part (ignore the seconds):
- PC: `lun 15 may 2023 12:13:51 CEST`
- Raspberry: `Mon May 15 12:14:14 CEST 2023`
- Create 3: `Mon May 15 10:14:40 UTC 2023`

**Comment by roni-kreinin** [comment]
The UTC and CEST timezones are 2 hours apart so this looks correct.

**Comment by Fran-FC** [comment]
> The UTC and CEST timezones are 2 hours apart so this looks correct.

Do you know how to change the timezone in the Create 3? I am not able to change it

**Comment by Fran-FC** [comment]
Despite having the same time the same problem occurs, can't connect frames published by Create3 with frames published by RP.

**Comment by roni-kreinin** [comment]
@Fran-FC Have you tried using the NTP sync feature on the Create 3 webserver? You can also use the `turtlebot4-ntpd-sync` alias on the RPi instead.

**Comment by Jayden-F** [comment]
@roni-kreinin I am curious regarding this incredibly frustrating ntp issue. Is this only an issue for the turtlebot4? Because it is based on two single board computers, where the odom data is published by the create3 and the lidar data from the RPI.

Or is common with robots in ROS1/2 to separate this information across different hardware systems?

**Comment by roni-kreinin** [comment]
@Jayden-F A two computer robot is not uncommon, and the setup that the TurtleBot 4 has with one computer running controls/odometry and the other running sensors is also not uncommon.

The issue with NTP is that the Create 3 often isn't accepting the time that the RPi is serving, and when the Create 3 is not connected to the internet over Wi-Fi it just continues to use its own incorrect time. This causes the `odom->base_link` transform to have incorrect/delayed time stamps when compared to the lidar data, so things like SLAM will not be able to function correctly.

I will try to escalate further with iRobot to find a solution for this issue.

**Comment by Yadunund** [comment]
> @Jayden-F A two computer robot is not uncommon, and the setup that the TurtleBot 4 has with one computer running controls/odometry and the other running sensors is also not common.

Yeah I agree. The problem here is exacerbated by the fact that the create3 board is more or less a black box.

**Comment by Fran-FC** [comment]
> @Fran-FC Have you tried using the NTP sync feature on the Create 3 webserver? You can also use the `turtlebot4-ntpd-sync` alias on the RPi instead.

I have tried this but the same happens. Even with a fresh restart.

**Comment by Fran-FC** [comment]
> @Jayden-F A two computer robot is not uncommon, and the setup that the TurtleBot 4 has with one computer running controls/odometry and the other running sensors is also not uncommon.
> 
> The issue with NTP is that the Create 3 often isn't accepting the time that the RPi is serving, and when the Create 3 is not connected to the internet over Wi-Fi it just continues to use its own incorrect time. This causes the `odom->base_link` transform to have incorrect/delayed time stamps when compared to the lidar data, so things like SLAM will not be able to function correctly.
> 
> I will try to escalate further with iRobot to find a solution for this issue.

A modifiable chrony configuration file has been requested as an enhancement for the next Create 3 Humble image, I hope that it doesn't take long to be released 🤞🏻

**Comment by hilary-luo** [comment]
This issue is being closed due to inactivity. If you are still experiencing the issue, feel free to reopen this ticket when you are ready to continue the troubleshooting process.
